### ISSUE TITLE
Date is getting reset when trying add time.

### ISSUE THREAD

**Issue by abhay187** [adam5909099/mantine-date-time-picker#1]
Hi, Thanks for creating must needed datetime picker. But this bug made it impossible for me to use it.
https://user-images.githubusercontent.com/61496865/214963717-7a174dfb-692d-43e0-a0f0-b36a390ace47.mov

**Comment by Akash187** [comment]
Hi @adam5909099,
I have created a pull request for the above issue https://github.com/adam5909099/mantine-date-time-picker/pull/2.

**Comment by abhay187** [comment]
Thanks, @Akash187 for the pull request.

**Comment by mindful-dev25** [comment]
Looks good to me, it's merged

**Comment by mindful-dev25** [comment]
@Akash187 I invited you to this repo. Feel free to deploy this one as public npm package

**Comment by Akash187** [comment]
Thanks, @adam5909099 will publish it as an npm package by the end of this week.

**Comment by mindful-dev25** [comment]
Awesome

**Comment by Akash187** [comment]
Hey, @adam5909099 package is published.
