### ISSUE TITLE
Time input spacing

### ISSUE THREAD

**Issue by derekbking** [adam5909099/mantine-date-time-picker#3]
It seems there should be a little bit of spacing between the days of the month and the time input. It's mainly noticeable if you have a day selected that falls on the bottom of the calendar view. As seen here 
![image](https://user-images.githubusercontent.com/3951143/215914703-0f196ab2-438d-4e2d-a30b-221c83d353d1.png)
The component looks much better when days higher up on the calendar are selected:
![image](https://user-images.githubusercontent.com/3951143/215914873-b9a7c14e-09ff-4eeb-9336-d717fd9801f8.png)

Here is an example with 12px of padding on the top.
![image](https://user-images.githubusercontent.com/3951143/215914995-550e961e-d38d-4826-a26a-afc5cd7da8d9.png)
![image](https://user-images.githubusercontent.com/3951143/215915016-88e27ac2-d160-4294-acff-996330b1c1f1.png)

**Comment by Akash187** [comment]
@derekbking thanks for reporting. It is fixed now.
