### ISSUE TITLE
NPM peer/dependencies 

### ISSUE THREAD

**Issue by jabinb** [adam5909099/mantine-date-time-picker#4]
Currently the `package.json` for this library specifies uses only `dependencies`. This causes all deps to be unnecessarily installed with the library in projects, including potentially conflicting versions (e.g. of React/Mantine).

https://github.com/adam5909099/mantine-date-time-picker/blob/5ad8dbca8affc96ad6147af008b2b3666a9c2568/package.json#L22-L41

For example `@types, @testing-library` dev-only etc packages should be in `devDependencies` and `React, @mantine, dayjs` etc should be in `peerDependencies`.

As a practical example check the [`@mantine/dates` `package.json`](https://github.com/mantinedev/mantine/blob/master/src/mantine-dates/package.json)

**Comment by mindful-dev25** [comment]
@jabinb I agree. I added you as a collaborator. Please feel free to make PR up to fix it.

**Comment by Akash187** [comment]
Got it @jabinb will fix this soon.

**Comment by Akash187** [comment]
Completed. Moved all the dependencies between dev and peer.
