### ISSUE TITLE
Support for 24h format

### ISSUE THREAD

**Issue by bowis** [adam5909099/mantine-date-time-picker#5]
Is it possible to have the time in a 24H format instead of AM/PM?

**Comment by Akash187** [comment]
Hey @Bowis it is possible just pass prop `inputFormat="DD/MM/YYYY hh:mm"`

**Comment by bowis** [comment]
@Akash187 small correction, it should be HH:mm for 24h

**Comment by Akash187** [comment]
Thanks for the correction @Bowis it will help others.
