### ISSUE TITLE
Support to change button labels

### ISSUE THREAD

**Issue by vobence** [adam5909099/mantine-date-time-picker#6]
It would be great if we can override the "Now" and "Ok" strings in the component. As I can see it's now hardcoded to the component.

**Comment by Akash187** [comment]
Hey, @vobence your suggestion looks valid considering support for other languages. Will update package soon.

**Comment by Akash187** [comment]
@vobence Fixed I have updated the package now you can pass props `nowLabel` and `okLabel`.
